name: Products API
on:
  push:
    branches: [devToProd]
#Jobs to run, could be multiple jobs
jobs:
  Products_API:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - name: Start Docker for MongoDB
        run: npm run docker-mongo
      - name: npm install, build, and test
        run: |
          npm run build --if-present
          npm run test --if-present
